/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IssuerRouteImport } from './routes/issuer'
import { Route as IndexRouteImport } from './routes/index'

const IssuerRoute = IssuerRouteImport.update({
  id: '/issuer',
  path: '/issuer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/issuer': typeof IssuerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/issuer': typeof IssuerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/issuer': typeof IssuerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/issuer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/issuer'
  id: '__root__' | '/' | '/issuer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IssuerRoute: typeof IssuerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/issuer': {
      id: '/issuer'
      path: '/issuer'
      fullPath: '/issuer'
      preLoaderRoute: typeof IssuerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IssuerRoute: IssuerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
